### ISSUE TITLE
App crashes when tapping forwarded email address

### ISSUE THREAD

**Issue by wAuner** [simple-login/Simple-Login-iOS#2]
When I tap on the email address that has been forwarded for a specific alias the app crashes.
Happens every time on ipadOS

**Comment by ntnhon** [comment]
Hi @wAuner, it is because iPad doesn't present an actionSheet (an alert that rises from bottom) as iPhone does. This is a typical bug and somehow I forgot about it in this project. Thanks a lot for pointing out.

It is fixed in this [commit](https://github.com/simple-login/Simple-Login-iOS/commit/f3c4584c8d733d767aa8a73ded0470fd2d446889).

I will make a new release for this fix and #1.
