### ISSUE TITLE
[Keyboard extension] Able to randomize aliases

### ISSUE THREAD

**Issue by sleeping10** [simple-login/Simple-Login-iOS#59]
Hi, feature request. Is it possible to add new alias from the keyboard extension? For example if you are creating alias outside safari in app or messaging alias to someone where you don't have share button.

Example
![image](https://user-images.githubusercontent.com/37278143/159186530-ddba1b64-8f77-43ac-8944-b36942a38110.jpeg)

**Comment by ntnhon** [comment]
Hello, technically it's possible but such "Create alias" button will complicate the UI. I'm not sure if it's worth doing. What do you think @nguyenkims?

**Comment by nguyenkims** [comment]
This is a good idea but indeed complicated to add in this version, I think we can add it in the next version.

**Comment by bradenglund** [comment]
Would it make sense to have it as a second keyboard? You could have one of existing and one that is to create a new alias.

**Comment by bradenglund** [comment]
I like it! Could a third/ fourth option be added where you create based on url prefix with preset domain?

**Comment by ntnhon** [comment]
@bradenglund thank you! I believe in most cases when users want more control over their aliases, they'd use the main app instead of the keyboard extension. I think it's better to keep the extension simple and compact. Please feel free to open a feature request [here](https://github.com/simple-login/app/discussions/categories/feature-requests), I'd love to see if people are interested in such option.

**Comment by bradenglund** [comment]
So I was viewing it as an efficient way to generate usernames for a site while adding a new login in bitwarden. I thought that could be one of the easiest ways to integrate with a password manager. I now see on [this post](https://github.com/simple-login/app/discussions/412) that maybe some progress is being made? Or at least we could use a catch-all domain for it through the new bitwarden generator.
